### ISSUE TITLE
Add "make" functions for ArrayBuffer, ArrayBufferView, and Blob

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/octo#18]
Create generators for ArrayBuffer, ArrayBufferView, and Blob.  These should be similar to the current make.array.filledArray.

**Comment by posidron** [comment]
https://github.com/MozillaSecurity/octo/commit/f098ea3b00173b7eeb2231543a653653c6c7c726#diff-8062071de42de0eaa8b248dcb4a0e803
