### ISSUE TITLE
Javascript Style

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/octo#6]
In order to maintain the same style across all modules, we should pick a single style to adhere to.  The Google style guide is fairly comprehensive - particularly in naming and casing conventions.

_In general, use functionNamesLikeThis, variableNamesLikeThis, ClassNamesLikeThis, EnumNamesLikeThis, methodNamesLikeThis, CONSTANT_VALUES_LIKE_THIS, foo.namespaceNamesLikeThis.bar, and filenameslikethis.js._

[https://google.github.io/styleguide/javascriptguide.xml](https://google.github.io/styleguide/javascriptguide.xml)
[https://google.github.io/styleguide/jsguide.html](https://google.github.io/styleguide/jsguide.html)

**Comment by nth10sd** [comment]
[Coding style page](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style) from MDN.

**Comment by posidron** [comment]
I am proposing https://github.com/feross/standard. 

* It is widely used and is integrated in (or has addon's for) most used IDE's and editors. 

* It uses ESLint under the hood. There is still the possibility in using "eslint-config-standard" if really needed.

* It seems future oriented by having the possibility in using a custom parser and by providing already testing routines for ES8 and language feature proposals that are in "Stage 4" of the proposal process.

* It is also possible for us to put 'standard' into the package.json and let it run on Travis-CI after each push.

**Comment by posidron** [comment]
The code base has adapted to the use of Standard.
