### ISSUE TITLE
Leverage Object.defineProperty rather than foo.prototype.bar

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/octo#7]
I believe that allot of our code, particularly related to "Objects", leverages foo.prototype.bar for adding new methods.  This may lead to unsafe enumeration of objects using for...in loops.  We should replace these instances where possible with Object.defineProperty.

**Comment by posidron** [comment]
https://github.com/MozillaSecurity/octo/blob/master/utils/prototypes.js
https://github.com/MozillaSecurity/octo/blob/master/utils/objects.js
